In [7]:
import numpy as np
arr1 = np.arange(1,17).reshape(4,4)
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [5]:
arr2 = np.arange(17,33).reshape(4,4)
print(arr2)

[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [10]:
arr_concat = np.concatenate((arr1,arr2))        # concatenate arr1 into arr2
print(arr_concat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [12]:
arr_conca = np.concatenate((arr1,arr2), axis = 1)    # row wise concatenate arr1 into arr2 
print(arr_conca)

[[ 1  2  3  4 17 18 19 20]
 [ 5  6  7  8 21 22 23 24]
 [ 9 10 11 12 25 26 27 28]
 [13 14 15 16 29 30 31 32]]


In [13]:
np.vstack((arr1,arr2))                            # concatenate arr1 and arr2 vertically

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [15]:
np.hstack((arr1,arr2))                             # concatenate arr1 and arr2 horizontally

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [27]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [21]:
li = np.split(arr1,2)                                 # split arr1 into two part
print(li)

[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]


In [20]:
print(type(li))                                         # after spliting array data type is list

<class 'list'>


In [26]:
li[1]                                                    # slice of index 1

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [29]:
np.split(arr1,2,axis = 1)                           # split column wise

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [30]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [37]:
np.split(arr1,[1,2])                               # multiple split 

[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]