In [1]:
import numpy as np

In [2]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(1,10).reshape(3,3)
print("Array 1:\n",arr1,"\n")
print("Array 2:\n",arr2)

Array 1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

Array 2:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
arr1+arr2                            # simple addition of array

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [4]:
np.add(arr1,arr2)                    # addition of array using function

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [5]:
arr1 - arr2                          # simple subtraction of array

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [6]:
np.subtract(arr1,arr2)               # subtract of array using function

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [7]:
arr1 / arr2                           # simple division of array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.divide(arr1,arr2)                 # division of array using function

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
arr1 * arr2                            # simple multiplication of array

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [10]:
np.multiply(arr1,arr2)                  # multiply of array using function

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [11]:
arr1 @ arr2                              # product of matrix (did multiply like first row first colum)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [12]:
arr1.dot(arr2)                          # using function we can get product of array

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [13]:
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
arr1.max()                         # search maximum value in the array

9

In [15]:
arr1.argmax()                     # searching index of max value in the array

8

In [16]:
arr1.max(axis = 0)              # searching colum wise of maximum value in the array

array([7, 8, 9])

In [17]:
arr1.max(axis = 1)              # searching row wise of maximum value in the array

array([3, 6, 9])

In [19]:
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
np.sum(arr1)                # return sum of array 1

45

In [23]:
np.sum(arr1 , axis = 0)     # return colum wise sum

array([12, 15, 18])

In [24]:
np.sum(arr1 , axis = 1)      # return row wise sum

array([ 6, 15, 24])

In [25]:
np.mean(arr1)             # return avarage value in the array

5.0

In [26]:
np.sqrt(arr1)            # return squre root of each element in the array

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])