In [17]:
import numpy as np         # importing numeric python module/library

# One dimentional Array

In [2]:
arr1=np.array([1,2,3,4])  # declaration of one dimentional array
print(arr1)

[1 2 3 4]


In [3]:
print(type(arr1))        # checking type of array

<class 'numpy.ndarray'>


In [4]:
arr1.ndim               # one dimentional array

1

In [7]:
arr1.size               # size of elements in array

4

In [11]:
arr1.shape             # shape of array in result(4,) (colum,rows)

(4,)

# Two dimentional Array

In [10]:
arr_2d=np.array([[1,2,3,4],[5,6,7,8]])    # declaration of 2 dimentional array 
print(arr_2d)


[[1 2 3 4]
 [5 6 7 8]]


In [12]:
print("Datatype:",type(arr_2d))            # type

Datatype: <class 'numpy.ndarray'>


In [13]:
print("Dimentional of array:",arr_2d.ndim)  # dimentional

Dimentional of array: 2


In [14]:
print("Size of elements:",arr_2d.size)     # size of elements in array

Size of elements: 8


In [15]:
arr_2d.shape                             # shape of array (rows,colum)

(2, 4)

In [16]:
arr_2d.dtype                            # checking type of elements in array

dtype('int32')