# NumPy Functions

In [2]:
import numpy as np             # imported numpy library

# arange()

In [4]:
# Syntax : np.arange(start,end,steps)
arr_1d=np.arange(1,13)                 # 1 inclusive number and 13 is exclusive number
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [15]:
even_arr=np.arange(2,13,2)          # print even numbers
print(even_arr)

[ 2  4  6  8 10 12]


# linspace()

In [29]:
lnspace=np.linspace(2,2,5)     # np.linspace(start,stop,number of samples bydefault 50 samples)
print(lnspace)

[2. 2. 2. 2. 2.]


# reshape()

In [30]:
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [42]:
ar_2d=arr_1d.reshape(2,6)             # reshaped 1d array into 2d array
print(ar_2d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [43]:
ar_2d.ndim                            # checking dimentional

2

In [39]:
ar_3d=arr_1d.reshape(2,2,3)           # reshaped 1d array into 3 d array
print(ar_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [44]:
ar_3d.ndim                            # checking dimentional

3

In [50]:
arr=np.arange(1,13).reshape(3,4)      # using arange function
print(arr)
print("\n""Array of Dimention",arr.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Array of Dimention 2


# ravel()

In [51]:
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [53]:
arr.ravel()               # converting multi dimentional array into 1d array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# flatten()

In [54]:
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [55]:
arr.flatten()            # converting multi dimentional into 1d array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

    NOTE : 
        ravel    method returns view of the original array ,it may modify the entries in the original array
        flatten  method always return a copy, it may not modify the entries 


# transpose()

In [60]:
ar_tr=np.arange(1,13).reshape(2,6)

print(ar_tr)
print("Shape of array:",ar_tr.shape)  

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Shape of array: (2, 6)


In [62]:
ar_tr.transpose()                   # converting rows to colum and colum to rows

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

In [65]:
ar_tr.T                               # we also can use either transpose to T for transpose the array

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])