In [1]:
import numpy as np

x = np.arange(5,9).reshape(2,2)
print(x[0])


[5 6]


In [2]:
y = np.indices((2,10))
print(y)

[[[0 0 0 0 0 0 0 0 0 0]
  [1 1 1 1 1 1 1 1 1 1]]

 [[0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]]]


In [3]:
for i in range(1,48):
    if i%3==0:
        print(i)

3
6
9
12
15
18
21
24
27
30
33
36
39
42
45


SyntaxError: invalid syntax (<ipython-input-4-a851001be6a7>, line 1)